[package]
name = "rust_processing_engine"
version = "0.1.0"
edition = "2024"

default-run = "rust_processing_engine"

[[bin]]
name = "benchSerial"
path = "src/benchmarks/benchmarkSerial.rs"

[[bin]]
name = "benchParallelCallback"
path = "src/benchmarks/benchmarkParallelCallback.rs"

[[bin]]
name = "benchParallelParsing"
path = "src/benchmarks/benchmarkParallelParsing.rs"

[[bin]]
name = "benchMmap"
path = "src/benchmarks/benchMmap.rs"

[dependencies]
csv = "1.4.0"
serde = {version = "1.0.229", features = ["derive"]}
memmap2 = "0.9"
memchr = "2.8.3"
mimalloc = "0.1"
indicatif = "0.18.6"

[profile.release]
debug = true
